export default [
    {
        id: 1,
        pid: 0,
        title: '系统设置',
        icon: 'icon-system',
        url: '',
        active: false,
    },
    // {
    //     id: 2,
    //     pid: 1,
    //     title: '接口设置',
    //     icon: 'icon-interface',
    //     url: '/interface',
    //     active: false
    // },
    {
        id: 3,
        pid: 1,
        title: '员工管理',
        icon: 'icon-user',
        url: '/user',
        active: false,
    },
    {
        id: 4,
        pid: 0,
        title: '账务信息',
        icon: 'icon-pay2',
        url: '',
        active: false,
    },
    {
        id: 5,
        pid: 4,
        title: '消费记录',
        icon: 'icon-pay',
        url: '/finance/expenseSheet',
        active: false,
    },
    {
        id: 6,
        pid: 4,
        title: '对账单',
        icon: 'icon-orderSystem',
        url: '/finance/checkBill',
        active: false,
    },
];
